"""
Feature Names Registry
================================================================================

Author: Abubakar Saeed
Created: January 2026
Last Modified: February 2026

Description:
    Centralized registry of all feature names generated by the BioGraphX
    pipeline. This module defines the complete 157-dimensional feature space
    with explicit naming conventions for each feature category.

    The feature space is organized into five distinct categories that capture
    complementary aspects of protein sequence and structure:

    1. BASIC_GRAPH_NAMES (85 features):
       Topological properties of residue interaction graphs including node/edge
       statistics, degree distributions, centrality measures, community
       structure, and localization patterns.

    2. HYBRID_FEATURE_NAMES (22 features):
       Enrichment scores for synergistic combinations of non-covalent
       interactions (e.g., salt bridge + hydrogen bond) that represent
       cooperative biochemical networks.

    3. SIGNAL_FEATURE_NAMES (20 features):
       Subcellular localization evidence combining sequence motif detection
       and hybrid interaction enrichment for 10 cellular compartments.

    4. PHYSICS_NAMES (19 features):
       Global physicochemical properties including isoelectric point, charge,
       hydrophobicity (GRAVY), autocorrelation periodicities, and sequence
       complexity metrics.

    5. FRUSTRATION_FEATURE_NAMES (11 features):
       Configurational frustration metrics quantifying local constraint
       satisfaction and energy landscape ruggedness.


Notes on Distance Metrics:
    IMPORTANT: All distance-derived features in graph topology (path lengths,
    diameter, radius) are computed on graphs where edge constraints are defined
    by LINEAR SEQUENCE DISTANCE thresholds. These features represent connectivity
    patterns in primary structure space, NOT Euclidean proximity in tertiary
    structure. This distinction is critical when interpreting features such as
    "Avg_Shortest_Path" and "Graph_Diameter".

================================================================================
"""

# =============================================================================
# 1. BASIC GRAPH FEATURES (85 dimensions)
# =============================================================================
# These features capture the topological organization of residue interaction
# networks constructed from 12 non-covalent interaction types. All distance
# thresholds used for edge construction are based on LINEAR SEQUENCE SEPARATION.
# =============================================================================
from typing import Dict, List
BASIC_GRAPH_NAMES = [
    # -------------------------------------------------------------------------
    # Basic topology metrics (3)
    # Fundamental graph size and density descriptors
    # -------------------------------------------------------------------------
    "Node_Count",  # Number of residues in graph
    "Edge_Count",  # Total number of interactions
    "Graph_Density",  # Edge density (2|E|/(|V|(|V|-1)))

    # -------------------------------------------------------------------------
    # Degree statistics (6)
    # Distribution of node connectivity (number of interaction partners)
    # -------------------------------------------------------------------------
    "Mean_Degree",  # Average number of interactions per residue
    "Degree_Std",  # Standard deviation of degree distribution
    "Max_Degree",  # Maximum node degree (hub residues)
    "Degree_Q1",  # First quartile of degree distribution
    "Degree_Median",  # Median degree
    "Degree_Q3",  # Third quartile of degree distribution

    # -------------------------------------------------------------------------
    # Weighted degree statistics (3)
    # Edge-weight normalized connectivity (strength)
    # -------------------------------------------------------------------------
    "Mean_Weighted_Degree",  # Average interaction strength per residue
    "Weighted_Degree_Std",  # Standard deviation of weighted degree
    "Max_Weighted_Degree",  # Maximum weighted degree

    # -------------------------------------------------------------------------
    # Interaction type composition (12)
    # Relative frequency of each non-covalent interaction class
    # -------------------------------------------------------------------------
    "Hydrophobic_Ratio",  # Proportion of hydrophobic interactions
    "HydrogenBond_Ratio",  # Proportion of hydrogen bonds
    "SaltBridge_Ratio",  # Proportion of electrostatic salt bridges
    "Pi_Interaction_Ratio",  # Proportion of π-π and π-cation interactions
    "Disulfide_Ratio",  # Proportion of disulfide bonds
    "CationPi_Ratio",  # Proportion of cation-π interactions
    "VanDerWaals_Ratio",  # Proportion of van der Waals contacts
    "CH_Pi_Ratio",  # Proportion of CH-π interactions
    "NH_Pi_Ratio",  # Proportion of NH-π interactions
    "CarbonylCarbonyl_Ratio",  # Proportion of carbonyl-carbonyl interactions
    "SulfurPi_Ratio",  # Proportion of sulfur-π interactions
    "Backbone_Ratio",  # Proportion of backbone-mediated interactions

    # -------------------------------------------------------------------------
    # Centrality metrics (12)
    # Node importance measures in the interaction network
    # -------------------------------------------------------------------------
    "Mean_Betweenness",  # Average betweenness centrality (bridge potential)
    "Betweenness_Std",  # Standard deviation of betweenness
    "Max_Betweenness",  # Maximum betweenness (critical bridges)
    "Min_Betweenness",  # Minimum betweenness
    "Betweenness_Q1",  # First quartile of betweenness
    "Betweenness_Q3",  # Third quartile of betweenness
    "Mean_Closeness",  # Average closeness centrality (accessibility)
    "Closeness_Std",  # Standard deviation of closeness
    "Max_Closeness",  # Maximum closeness
    "Min_Closeness",  # Minimum closeness
    "Mean_Eigenvector",  # Average eigenvector centrality (hub connectivity)
    "Eigenvector_Std",  # Standard deviation of eigenvector centrality

    # -------------------------------------------------------------------------
    # Community structure (8)
    # Modular organization and clustering patterns
    # -------------------------------------------------------------------------
    "Community_Count",  # Number of detected communities/modules
    "Modularity",  # Modularity score (Q) - community strength
    "Mean_Community_Size",  # Average community size
    "Community_Size_Std",  # Standard deviation of community sizes
    "Max_Community_Size",  # Largest community size
    "Min_Community_Size",  # Smallest community size
    "IntraCommunity_Edge_Ratio",  # Fraction of edges within communities
    "InterCommunity_Edge_Ratio",  # Fraction of edges between communities

    # -------------------------------------------------------------------------
    # Localization and domain patterns (20)
    # Sequence position-specific network properties
    # -------------------------------------------------------------------------
    "N_Term_Hydrophobic_Density",  # Hydrophobic interaction density in N-terminus
    "N_Term_Basic_Centrality",  # Centrality of basic residues in N-terminus
    "N_Term_Clustering",  # Clustering coefficient in N-terminal region
    "N_Term_Edge_Density",  # Edge density in N-terminal region
    "C_Term_Surface_Exposure",  # Predicted surface exposure in C-terminus
    "C_Term_Charged_Connectivity",  # Charged residue connectivity in C-terminus
    "C_Term_Terminal_Degree",  # Degree of C-terminal residues
    "Basic_Residue_Connectivity",  # Overall connectivity of basic residues
    "Basic_Cluster_Centrality",  # Centrality of basic residue clusters
    "Basic_Cluster_Count",  # Number of basic residue clusters
    "Max_Basic_Cluster_Size",  # Size of largest basic cluster
    "Hydrophobic_Cluster_Connectivity",  # Connectivity of hydrophobic clusters
    "Hydrophobic_External_Edges",  # Cross-cluster hydrophobic edges
    "Hydrophobic_Cluster_Count",  # Number of hydrophobic clusters
    "Max_Hydrophobic_Cluster",  # Size of largest hydrophobic cluster
    "Mean_Hydrophobic_Cluster_Size",  # Average hydrophobic cluster size
    "N_Term_Basic_Density",  # Density of basic residues in N-terminus
    "Basic_Gradient",  # N→C gradient of basic residue frequency
    "Acidic_Gradient",  # N→C gradient of acidic residue frequency
    "Net_Charge_Density",  # Net charge per residue

    # -------------------------------------------------------------------------
    # Path-based metrics (6)
    # Distance and efficiency measures in the interaction network
    # NOTE: All path lengths represent steps in the graph (edge traversals),
    # NOT 3D Euclidean distances or angstrom measurements.
    # -------------------------------------------------------------------------
    "Avg_Shortest_Path",  # Average shortest path length between all node pairs
    "Graph_Diameter",  # Maximum shortest path length (graph diameter)
    "Global_Efficiency",  # Average inverse shortest path length
    "Local_Efficiency",  # Efficiency of local subgraphs
    "Path_Length_Std",  # Standard deviation of path lengths
    "Max_Path_Length",  # Maximum path length (diameter alternative)

    # -------------------------------------------------------------------------
    # Additional topological metrics (15)
    # Supplementary graph descriptors
    # -------------------------------------------------------------------------
    "Clustering_Coefficient",  # Average local clustering coefficient
    "Assortativity",  # Degree correlation coefficient
    "Graph_Radius",  # Minimum eccentricity
    "Triangle_Count",  # Number of 3-cycles in the graph
    "N_Region_Density",  # Edge density in N-terminal region
    "M_Region_Density",  # Edge density in middle region
    "C_Region_Density",  # Edge density in C-terminal region
    "Mean_Edge_Weight",  # Average interaction strength
    "Edge_Weight_Std",  # Standard deviation of edge weights
    "Max_Edge_Weight",  # Maximum interaction strength
    "Min_Edge_Weight",  # Minimum interaction strength
    "Edge_Weight_Q1",  # First quartile of edge weights
    "Edge_Weight_Median",  # Median edge weight
    "Edge_Weight_Q3",  # Third quartile of edge weights
    "Edge_Weight_Range"  # Range of edge weights (max - min)
]

# =============================================================================
# 2. HYBRID INTERACTION FEATURES (22 dimensions)
# =============================================================================
# These features quantify synergistic combinations of non-covalent interactions
# that co-occur between residue pairs, representing cooperative biochemical
# effects with enhanced functional significance.
# =============================================================================

HYBRID_FEATURE_NAMES = [
    # -------------------------------------------------------------------------
    # Basic hybrid interaction scores (9)
    # Normalized enrichment scores for specific interaction combinations
    # -------------------------------------------------------------------------
    "SaltBridge_HBond_Hybrid",  # Salt bridge + hydrogen bond synergy
    "Hydrophobic_Pi_Hybrid",  # Hydrophobic + π-interaction synergy
    "CationPi_HBond_Hybrid",  # Cation-π + hydrogen bond synergy
    "Hydrophobic_VDW_Hybrid",  # Hydrophobic + van der Waals synergy
    "Pi_Cation_HBond_Hybrid",  # π-interaction + cation-π + hydrogen bond
    "CH_Pi_Hydrophobic_Hybrid",  # CH-π + hydrophobic synergy
    "Sulfur_Aromatic_Hybrid",  # Sulfur-π + aromatic interaction synergy
    "Carbonyl_Charge_Hybrid",  # Carbonyl-carbonyl + salt bridge synergy

    # -------------------------------------------------------------------------
    # Regional hybrid interaction density (4)
    # Spatial distribution of synergistic interactions
    # -------------------------------------------------------------------------
    "N_Terminal_Hybrid_Density",  # Hybrid interaction density in N-terminus
    "C_Terminal_Hybrid_Density",  # Hybrid interaction density in C-terminus
    "Hydrophobic_Region_Hybrid_Density",  # Hybrid density in hydrophobic domains
    "Basic_Region_Hybrid_Density",  # Hybrid density in basic residue clusters

    # -------------------------------------------------------------------------
    # Hybrid network properties (4)
    # Graph-theoretic metrics restricted to hybrid interaction edges
    # -------------------------------------------------------------------------
    "Hybrid_Edge_Ratio",  # Proportion of edges with hybrid character
    "Hybrid_Subgraph_Density",  # Edge density in hybrid-only subgraph
    "Hybrid_Network_Path_Length",  # Average path length in hybrid network
    "Hybrid_Cluster_Count",  # Number of hybrid interaction clusters

    # -------------------------------------------------------------------------
    # Hybrid co-occurrence patterns (3)
    # Multi-way interaction synergies
    # -------------------------------------------------------------------------
    "Hybrid_Cooccurrence_1",  # Primary hybrid co-occurrence pattern
    "Hybrid_Cooccurrence_2",  # Secondary hybrid co-occurrence pattern
    "Hybrid_Cooccurrence_3",  # Tertiary hybrid co-occurrence pattern

    # -------------------------------------------------------------------------
    # Advanced hybrid metrics (3)
    # Global hybrid network characteristics
    # -------------------------------------------------------------------------
    "Hybrid_Diversity",  # Shannon entropy of hybrid type distribution
    "Hybrid_Network_Centrality",  # Average centrality in hybrid network
    "Hybrid_Clustering"  # Clustering coefficient in hybrid network
]

# =============================================================================
# 3. SUBCELLULAR LOCALIZATION SIGNAL FEATURES (20 dimensions)
# =============================================================================
# Paired features for 10 subcellular compartments combining:
#   - Residue-based motif scores (canonical targeting signals)
#   - Hybrid interaction enrichment scores (graph-derived evidence)
# =============================================================================

TARGETING_SIGNAL_NAMES = [
    # Residue scores (10)
    "Signal_Nucleus_Residue", "Signal_Nucleus_Hybrid",
    "Signal_Mitochondrion_Residue", "Signal_Mitochondrion_Hybrid",
    "Signal_Extracellular_Residue", "Signal_Extracellular_Hybrid",
    "Signal_Cell_membrane_Residue", "Signal_Cell_membrane_Hybrid",
    "Signal_Endoplasmic_reticulum_Residue", "Signal_Endoplasmic_reticulum_Hybrid",
    "Signal_Golgi_apparatus_Residue", "Signal_Golgi_apparatus_Hybrid",
    "Signal_Lysosome_Vacuole_Residue", "Signal_Lysosome_Vacuole_Hybrid",
    "Signal_Peroxisomal_Residue", "Signal_Peroxisomal_Hybrid",
    "Signal_Plastid_Residue", "Signal_Plastid_Hybrid",
    "Signal_Cytoplasm_Residue", "Signal_Cytoplasm_Hybrid"
]

# =============================================================================
# 4. GLOBAL PHYSICOCHEMICAL PROPERTIES (19 dimensions)
# =============================================================================
# Sequence-derived biophysical features independent of graph construction.
# Includes electrostatic, hydrophobic, and complexity metrics.
# =============================================================================

PHYSICS_NAMES = [
    # -------------------------------------------------------------------------
    # Electrostatic properties (4)
    # -------------------------------------------------------------------------
    "Isoelectric_Point",  # Theoretical pI (pH of zero net charge)
    "Net_Charge",  # Total charge at pH 7.0
    "Charge_Density_Physics",  # Charge per residue (normalized)
    "GRAVY",  # Grand Average of Hydropathicity (Kyte-Doolittle)

    # -------------------------------------------------------------------------
    # Compositional properties (2)
    # -------------------------------------------------------------------------
    "Aromaticity",  # Frequency of aromatic residues (F, Y, W)
    "Instability_Proxy",  # Frequency of P,E,S,T,Q,D (PEST region proxy)

    # -------------------------------------------------------------------------
    # Hydrophobicity autocorrelation (6 features: lags 1-6)
    # Periodicity of hydrophobic pattern along sequence
    # NOTE: Lags represent LINEAR SEQUENCE POSITION separation
    # -------------------------------------------------------------------------
    "Hydro_Corr_L1", "Hydro_Corr_L2", "Hydro_Corr_L3",
    "Hydro_Corr_L4", "Hydro_Corr_L5", "Hydro_Corr_L6",

    # -------------------------------------------------------------------------
    # Charge autocorrelation (6 features: lags 1-6)
    # Periodicity of electrostatic charge pattern
    # NOTE: Lags represent LINEAR SEQUENCE POSITION separation
    # -------------------------------------------------------------------------
    "Charge_Corr_L1", "Charge_Corr_L2", "Charge_Corr_L3",
    "Charge_Corr_L4", "Charge_Corr_L5", "Charge_Corr_L6",

    # -------------------------------------------------------------------------
    # Sequence complexity (1)
    # -------------------------------------------------------------------------
    "Shannon_Entropy"  # Amino acid diversity (bits)
]

# =============================================================================
# 5. CONFIGURATIONAL FRUSTRATION FEATURES (11 dimensions)
# =============================================================================
# Metrics quantifying local constraint satisfaction and energetic conflicts
# within the residue interaction network. Frustration indicates regions where
# observed interactions conflict with expected optimal packing.
# =============================================================================

FRUSTRATION_FEATURE_NAMES = [
    # -------------------------------------------------------------------------
    # Regional frustration statistics (6)
    # -------------------------------------------------------------------------
    "Frustration_NTerminal_Mean",  # Average frustration in N-terminal 50 residues
    "Frustration_CTerminal_Mean",  # Average frustration in C-terminal 30 residues
    "Frustration_Structural_Mean",  # Average frustration in structural core
    "Frustration_SignalVsStructure",  # Frustration difference: signal vs structural
    "Frustration_MaxInSignalRegion",  # Maximum frustration within signal peptides
    "Frustration_Localization",  # Frustration in predicted localization domains

    # -------------------------------------------------------------------------
    # Global frustration metrics (5)
    # -------------------------------------------------------------------------
    "Frustration_HotspotCount",  # Number of highly frustrated residues
    "Frustration_SatisfactionRatio",  # Proportion of minimally frustrated edges
    "Frustration_Signal_Correlation",  # Correlation with frustration reference profiles
    "Frustration_HighSignalFrustration",  # Frustration enrichment in high-signal regions
    "Frustration_PerResidue_Mean"  # Global average frustration per residue
]

# =============================================================================
# 6. COMPLETE FEATURE VECTOR (157 dimensions)
# =============================================================================
# Master list of all 157 features in the exact concatenation order used by
# BioGraphXPipeline.extract_full_features(). This ordering must be maintained
# for model compatibility and feature interpretation.
# =============================================================================

COMPLETE_FEATURE_NAMES = (
        BASIC_GRAPH_NAMES +  # 85 features: topology and network metrics
        HYBRID_FEATURE_NAMES +  # 22 features: synergistic interactions
        TARGETING_SIGNAL_NAMES +  # 20 features: localization evidence (2 × 10)
        PHYSICS_NAMES +  # 19 features: global biophysical properties
        FRUSTRATION_FEATURE_NAMES  # 11 features: configurational frustration
)

# =============================================================================
# FEATURE CATEGORY INDICES (for subset selection)
# =============================================================================
# These indices enable selective access to specific feature categories without
# hardcoding positions throughout the codebase.
# =============================================================================

FEATURE_RANGES = {
    'basic_graph': (0, 85),
    'hybrid': (85, 107),  # 85 + 22 = 107
    'targeting_signal': (107, 127),  # 107 + 20 = 127
    'physics': (127, 146),  # 127 + 19 = 146
    'frustration': (146, 157)  # 146 + 11 = 157
}


def get_feature_category(category: str) -> List[str]:
    """
    Retrieve feature names for a specific analytical category.

    Parameters
    ----------
    category : str
        One of: 'basic_graph', 'hybrid', 'targeting_signal', 'signal',
        'profile', 'physics', 'frustration'

    Returns
    -------
    List[str]
        Feature names belonging to the specified category.

    Raises
    ------
    KeyError
        If category is not recognized.
    """
    if category == 'basic_graph':
        return BASIC_GRAPH_NAMES
    elif category == 'hybrid':
        return HYBRID_FEATURE_NAMES
    elif category in {'targeting_signal', 'signal', 'profile'}:
        return TARGETING_SIGNAL_NAMES
    elif category == 'physics':
        return PHYSICS_NAMES
    elif category == 'frustration':
        return FRUSTRATION_FEATURE_NAMES
    else:
        raise KeyError(
            f"Unknown feature category: {category}. "
            f"Valid categories: ['basic_graph', 'hybrid', 'targeting_signal', 'signal', 'profile', 'physics', 'frustration']"
        )


# =============================================================================
# VALIDATION
# =============================================================================
# Verify total feature count matches expected dimensionality
# =============================================================================

assert len(COMPLETE_FEATURE_NAMES) == 157, \
    f"Feature dimension mismatch: expected 157, got {len(COMPLETE_FEATURE_NAMES)}"
assert len(BASIC_GRAPH_NAMES) == 85, \
    f"Basic graph features: expected 85, got {len(BASIC_GRAPH_NAMES)}"
assert len(HYBRID_FEATURE_NAMES) == 22, \
    f"Hybrid features: expected 22, got {len(HYBRID_FEATURE_NAMES)}"
assert len(TARGETING_SIGNAL_NAMES) == 20, \
    f"Targeting signal features: expected 20, got {len(TARGETING_SIGNAL_NAMES)}"
assert len(PHYSICS_NAMES) == 19, \
    f"Physics features: expected 19, got {len(PHYSICS_NAMES)}"
assert len(FRUSTRATION_FEATURE_NAMES) == 11, \
    f"Frustration features: expected 11, got {len(FRUSTRATION_FEATURE_NAMES)}"